### ISSUE TITLE
BuildConfig field for 'Perform builds in OpenShift' build step in Jenkins configure Job form is populated with default value of 'frontend' instead of actual stored value.

### ISSUE THREAD

**Issue by arsogukpinar** [openshift/jenkins-plugin#10]
Description of problem:

Jenkins job configuration page doesn't present the actual value stored for buildConfig field of a 'Perform builds in OpenShift'  build step.

Version-Release number of selected component (if applicable):
OSE v3.1 

docker.io/openshift/jenkins-1-centos7                       latest              212bac2225d0        6 days ago          655.4 MB

How reproducible:
- Create a Jenkins Build Job with 'Perform builds in OpenShift' 
- Set BuildConfig value other than  'frontend' and save the build job
- Click on Configure job link.  

Actual results:

BuilConfig filed will be populated with 'frontend' value

Expected results:

BuildConfig form field populated with the actual value

Additional info:

Builds using a build config with a different name than 'frontend' is working hence, it is just a form population issue.

**Comment by gabemontero** [comment]
I have reproduced and have a fix in hand.  I'll consolidate with a couple of other small changes I have and commit upstream sometime tomorrow, followed then by starting the process of getting an update to the Jenkins Update Center, followed by updates to the OpenShift Jenkins images for centos and rhel.

thanks

**Comment by gabemontero** [comment]
fyi @arsogukpinar I've pushed the fix for this to the repo (if you want to build the plugin yourself and install to your jenkins env) and have initiated the publish to the jenkins update center.  It will be v1.0.5.

I'll update this and close this issue once the update center process is complete.

**Comment by gabemontero** [comment]
the rhel and ccentos versions of the jenkins image now have v1.0.5 of the plugin, which has the fix for this.

Closing this out.
