### ISSUE TITLE
Add Support for Getting Information About Existing Objects

### ISSUE THREAD

**Issue by dusura** [openshift/jenkins-plugin#110]
Hi,

any plans to add the ability to get information about existing objects similar to the CLI "oc get/describe ..."? I would like to write pipelines that use existing object information as inputs. Looking at the source "openshiftExec" seems about the closest thing that exists at the moment.

Cheers

**Comment by bparees** [comment]
No immediate plans but i think it's something we'd consider.

in the meantime you'd have to use a shell step to invoke the oc tooling directly (which is available in the image)

**Comment by dusura** [comment]
Thanks for the reply. Hopefully it's something that can be done sometime. Meantime, I will use oc as you suggest.

**Comment by gabemontero** [comment]
Opened https://trello.com/c/ca8QygYj/1090-jenkins-pipeline-plugin-oc-get-describe-equivalents on our trello board to track this enhancement request.
