### ISSUE TITLE
Snapshot dependency

### ISSUE THREAD

**Issue by dcw312** [openshift/jenkins-plugin#111]
Please forgive me if I'm in the wrong repo. I'm getting maven errors because of the inclusion of the openshift-restclient-java:5.2.0-SNAPSHOT in openshift-pipeline:1.0.32. Is there a release version available at http://repo.jenkins-ci.org/releases/com/openshift/jenkins/openshift-pipeline without the snapshot dependency (or another workaround)? 

>         <dependency>
>             <groupId>com.openshift</groupId>
>             <artifactId>openshift-restclient-java</artifactId>
>             <version>5.2.0-SNAPSHOT</version>
>         </dependency>

**Comment by gabemontero** [comment]
A 5.2.0-Final of openshift-restclient-java was just cut a couple of days ago (I had been periodically checking for this, but the timing of this issue is golden :-) ). We should be able to switch to that.
I'll do some regression testing to see if that is in fact the case.

@bparees fyi

**Comment by gabemontero** [comment]
My attempts to leverage 5.2.0-FINAL from https://repository.jboss.org/nexus/content/repositories/releases/com/openshift/openshift-restclient-java/5.2.0.Final/ are not working.  It is possible that the publishing process is not fully complete yet.

**Comment by gabemontero** [comment]
@dcw312 - 5.2.0-SNAPSHOT is available from the repository: http://repository.jboss.org/nexus/content/groups/public/com/openshift/openshift-restclient-java/

I couldn't tell if your were trying to build openshift-pipeline or list it as a dependency.  If the later, you could add that repository to your pom.xml and I would think be able to download 5.2.0-SNAPSHOT

**Comment by gabemontero** [comment]
Sorted things out ... dep now at 5.2.0.Final with commit https://github.com/openshift/jenkins-plugin/commit/3a7aad8fa32281750444f141b5229e3a621e6e05
