### ISSUE TITLE
"Trigger OpenShift Deployment" should accept an image tag

### ISSUE THREAD

**Issue by andyevans** [openshift/jenkins-plugin#114]
As documented:
_"Trigger OpenShift Deployment": performs the equivalent of an oc deploy --latest command invocation; it will monitor the resulting ReplicationController's "openshift.io/deployment.phase" annotation to confirm success_

Defaulting the `oc deploy` command to use `--latest` seems a bit limiting. What i'd like to be able to do is build an image, perform a successful deployment to a development environment, tag the image, then make sure this tag of the image is progressed through subsequent environments. How would one deploy an older version of an image? At the moment it wouldn't be possible without modifying the deployment config. What if a new `latest` image makes it's way into the registry while a deployment is awaiting approval to deploy to an environment?

Please forgive me if i've missed something here.

Thanks

**Comment by bparees** [comment]
you would tag an older version of the image into the imagestream that the deployment is based on, and trigger a deployment to deploy it.

i don't know what else you'd expect triggering a deployment to do, oc deploy does not offer a "deploy this image" option.  deployments deploy the thing they are pointing at, if you want to deploy something else, you have to change either what they are pointing at, or the thing they point to.

**Comment by andyevans** [comment]
okay so if i'm understanding correctly, to achieve what i'm after, once i verify a deployment to a DEV environment is successful i should tag the image into a new imagestream and have (for example) the 'SIT' DeploymentConfig with a Trigger listening to image changes on the new imagestream? So we have separate ImageStreams for each target deployment environment/namespace?

I'm trying to wrap my head around how to progress an image through a deployment lifecycle, i.e. from build through various environments and gates then through to production. Having a separate image stream for each is a new concept, pre-openshift you would handle this with image tags.

I realise this is largely a deployment architecture question and i'm likely asking this in the wrong place.

**Comment by bparees** [comment]
> once i verify a deployment to a DEV environment is successful i should tag the image into a new imagestream and have (for example) the 'SIT' DeploymentConfig with a Trigger listening to image changes on the new imagestream?

that would be a very typical way to set things up, yes.

> So we have separate ImageStreams for each target deployment environment/namespace?

or at least separate ImageStreamTags within the ImageStream

you may find this doc of interest (still a work in progress):  https://github.com/gabemontero/openshift-docs/blob/6a77acd34de23a9164b9940c83089d85a3502b31/dev_guide/application_lifecycle/application_promotion.adoc

**Comment by bparees** [comment]
you can also take a look at our sample jenkins job which does promotion from dev to prod:
https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/configuration/jobs/OpenShift%20Sample/config.xml

there is a tutorial associated w/ that job here:
https://github.com/openshift/origin/tree/master/examples/jenkins

and the summary of what the job does when run:

```
It will trigger an OpenShift build of the application, wait for the build to result in a deployment, confirm the new deployment works, and then tag the image for production. This tagging will trigger another deployment, this time creating/updating the production service.
```

**Comment by andyevans** [comment]
Thanks a lot for your help Ben.I suppose wrapping your head around the reliance on image streams to trigger deployments m is one of the fundamental things here. We ended up following a similar approach to the one you describe. Build and deploy an image to a development environment, execute sufficient tests and verifications, tag the image with the Jenkins build number,m. When we want to promote to any other environment we just again tag that image with 'environment name' (I.e. sit). We then have a deployment config listening for new instance of this image.Working well so far. Again many thanks for your help.
        _____________________________

**Comment by bparees** [comment]
yup, imagestreams and deployments and the relationship between them are fundamental building blocks for the platform.  Glad to help!
