### ISSUE TITLE
Patch / Update resources

### ISSUE THREAD

**Issue by MarkRx** [openshift/jenkins-plugin#121]
Hello,

Are there plans to be able to patch or update resources? I'm investigating the use of this plugin for deployments but I can't find a native jenkins way to perform patches or updates on existing resources. It would probably be used in conjunction with #110.

**Comment by bparees** [comment]
we're potentially looking at a secondary plugin that would expose the oc client more directly and would therefore expose things like apply.

we're hesitant to keep expanding this plugin to encompass every aspect of the oc tool.  Not saying we won't do this particular item, but there is a tension about at what point it makes more sense to just shell out to oc to do certain things vs implementing jenkins build steps for each and every oc operation.

**Comment by bparees** [comment]
you can see a draft of the new plugin here, would be interested in your feedback: https://github.com/jupierce/openshift-jenkins-pipeline-dsl

**Comment by bparees** [comment]
@jupierce fyi

**Comment by gabemontero** [comment]
+1 to everything @bparees noted (was comprising a similar update when I saw this one posted).

That said, I've updated the corresponding [trello card](https://trello.com/c/ca8QygYj/1090-jenkins-pipeline-plugin-oc-get-describe-equivalents-jenkins-integration) for get/describe to include patch/update as well.

**Comment by jupierce** [comment]
@MarkRx The example to look to is here: https://github.com/jupierce/openshift-jenkins-pipeline-dsl#need-to-update-an-object-without-replacing-it

Please let me know if you have any thoughts.

**Comment by MarkRx** [comment]
Yup. I have it built and am trying it and have submitted an issue :) 

https://github.com/jupierce/openshift-jenkins-pipeline-dsl/issues/1

**Comment by MarkRx** [comment]
Would it need to be a separate plugin? Why not just make a step to run raw commands that integrates the code from https://github.com/jupierce/openshift-jenkins-pipeline-dsl?

**Comment by gabemontero** [comment]
That is in fact one path under consideration.
Even entirely rebasing the old plugin on top of the new  one may happen
long term.

**Comment by bparees** [comment]
we're going to provide this functionality via the new plugin, rather than also backport it to the existing plugin, so closing this issue.
