### ISSUE TITLE
Deployments don't work

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#128]
Hello. We have just upgraded the Origin cluster to:

> [root@openshift-master1 ~]# oc version
oc v1.4.1
kubernetes v1.4.0+776c994
features: Basic-Auth GSSAPI Kerberos SPNEGO

>Server https://openshift-master1.i.drweb.ru:8443
openshift v1.4.1
kubernetes v1.4.0+776c994

and deployments stopped working. We cannot trigger an deployment (but it was created), and we got an error when starts it by hand:

> --> Scaling testing-drweb-mail-servers-11.0.3-auto-centos-7-1 to 1
--> Error listing events for replication controller testing-drweb-mail-servers-11.0.3-auto-centos-7-1: User "system:serviceaccount:drweb-maild:deployer" cannot list events in project "drweb-maild"
error: couldn't scale testing-drweb-mail-servers-11.0.3-auto-centos-7-1 to 1: User "system:serviceaccount:drweb-maild:deployer" cannot watch replicationcontrollers in project "drweb-maild"

**Comment by livelace** [comment]
Builds are working fine.

**Comment by bparees** [comment]
if you're also having issues running deployments by hand, this should be opened against origin.  (it sounds like your permissions in your cluster are incorrect).  Can you open this there and we'll get the right people to look at it?

**Comment by livelace** [comment]
@bparees Hello, yes. I was scared :) @kargakis helped me on freenode :)
