### ISSUE TITLE
About the jenkins-pipeline-plugin vs. the BuildTrigger/DeployTrigger in openshift

### ISSUE THREAD

**Issue by thincal** [openshift/jenkins-plugin#13]
It seems that the BuildTrigger / DeployTrigger in openshift already support finely, where the generic webhook buildtrigger and the imagechange deploy trigger could almost build and deploy automatically.

So that what will this jenkins-pipeline-plugin do besides that ? Many thanks for your any info.

**Comment by gabemontero** [comment]
Hi @thincal , sorry for the delay in responding (I was out of the office for a bit).  Even though you have closed the issue, I wanted to provide a few of points for you to consider:
1) The steps related to build and deploy don't just trigger the action; there is logic to verify whether the action completed successfully, beyond what is available with the webhooks
2) We also expose image stream tagging and polling (which connects the versioning semantics in OpenShift with the promotion semantics in Jenkins
3) We also provide means for creating API object in the OpenShift  server.

Hope that helps.  Thanks.

**Comment by thincal** [comment]
Thanks for your info, it helps.
