### ISSUE TITLE
FR: Support of variables inside Openshift Exec

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#135]
Hello. In Origin 1.5 appeared a new functionality - StatefulSet, which allows to be sure of a pod name. It would be great if "Openshift Exec" could support variables (pod name, container name, timeout, command, arguments  etc. ) :)

**Comment by gabemontero** [comment]
hi @livelace - I need to clarify what you mean by "support variables"

Are you saying you would like to define job build parameters / env vars and then reference them as the pod name, container name, arguments values you supply to the job definition?

i.e. for the pod name, you seed the job with ${MY_POD_NAME}, and then you define that as a build param for the job?

If so, while we are generally shutting down new development with this plugin in favor of https://github.com/openshift/jenkins-client-plugin (where you should be able to use $env.MY_POD_NAME), this change is pretty small / trivial (and one could argue should have been done originally), and I might be able to squeeze it in, pending agreement from @bparees

**Comment by bparees** [comment]
@gabemontero if it's trivial to add support for this to all the arg fields for the plugin steps (not just this step), it's probably worth doing.  if it's a one off for this step, it's just a slippery slope...

**Comment by livelace** [comment]
> Are you saying you would like to define job build parameters / env vars and then reference them as the pod name, container name, arguments values you supply to the job definition?

> i.e. for the pod name, you seed the job with ${MY_POD_NAME}, and then you define that as a build param for the job?

Yes, absolutely. 

>If so, while we are generally shutting down new development with this plugin in favor of https://github.com/openshift/jenkins-client-plugin (where you should be able to use $env.MY_POD_NAME), this change is pretty small / trivial (and one could argue should have been done originally), and I might be able to squeeze it in, pending agreement from @bparees

Yes, it's a trivial change and we need it :) Yes, we use DSL plugin, thanks for that, but DSL/pipeline/groovy are not so easy for newbies and this plugin allows very quickly assemble a simple (relative complex)  task/deployment/service. For instance - we use DSL plugin at the top of complex workflows, those contains numerous dependencies of CI , but at the bottom layers lay more simple tasks, which are created by this plugin.

**Comment by gabemontero** [comment]
On Tue, May 16, 2017 at 1:58 PM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> if it's trivial to add
> support for this to all the arg fields for the plugin steps (not just this
> step), it's probably worth doing. if it's a one off for this step, it's
> just a slippery slope...
>
It is just a portion of this step @bparees.  In general we support var
substitution for config fields, including several of the "base" params in
the oc exec step.
The  pod/container/args fields specific to oc exec were omitted.

**Comment by gabemontero** [comment]
On Tue, May 16, 2017 at 2:09 PM, Oleg Popov <notifications@github.com>
wrote:

> Are you saying you would like to define job build parameters / env vars
> and then reference them as the pod name, container name, arguments values
> you supply to the job definition?
>
> i.e. for the pod name, you seed the job with ${MY_POD_NAME}, and then you
> define that as a build param for the job?
>
> Yes, absolutely.
>
OK thanks for the confirmation.  Given the response from @bparees, I'll see
about adding this in the next few days.

**Comment by livelace** [comment]
@gabemontero @bparees 

Thanks, guys :)

**Comment by gabemontero** [comment]
@livelace if you can try out the pre-release version of this change at https://ci.openshift.redhat.com/jenkins/view/All/job/openshift-pipeline-plugin/36/s3/download/openshift-pipeline.hpi

**Comment by livelace** [comment]
@gabemontero It seems that all parameters work fine. I have checked all of them :) Thanks for your fast response/improvement :)

PS. Are there any restrictions of number of arguments ?

**Comment by gabemontero** [comment]
On Wed, May 17, 2017 at 11:18 AM, Oleg Popov <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> It seems that all
> parameters work fine. I have checked all of them :) Thanks for your fast
> response/improvement :)
>
Sounds good.  Glad to help.  Thanks for testing.

> PS. Are there any restrictions of number of arguments ?
>
No.  It is an unbounded Java List.
