### ISSUE TITLE
BUG: OpenshiftExec ignores timeout 

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#139]
@gabemontero 

Hello. Yesterday I tested FR https://github.com/openshift/jenkins-plugin/issues/135, I set an environment variable ${TIMEOUT} to 10 seconds and did "sleep 30" inside OpenshiftExec, all worked as expected. Today I try to exec a heavy script and I get  a timeout error - https://paste.fedoraproject.org/paste/H5NYxUjiZtkeEuFvQh58xF5M1UNdIGYhyRLivL9gydE=/raw
I tried to set global and local timeout, but it didn't help.

PS. This morning I upgraded to 1.0.43.

**Comment by gabemontero** [comment]
The error being reported here stems from the restclient/okhttp3 client timing out, where we essentially have a long running REST call.  The application of timeout in the step was not applied to the restclient/okhttp3 client timeout configuration.

We should augment our configuration of that client for this step to do that.

**Comment by gabemontero** [comment]
NOTE @livelace - you'll need to set the timeout in the step's advanced tab section

**Comment by livelace** [comment]
@gabemontero It's not a problem if it will work as expected. Every task usually has a dedicated timeout (different complexity).

**Comment by gabemontero** [comment]
[jenkins-plugin.zip](https://github.com/openshift/jenkins-plugin/files/1011644/jenkins-plugin.zip)

ok good @livelace 

before pushing this fix to the repo, if you don't mind, I'd like for you to try the plugin I've attached here; I'm not 100% certain I can construct a long running exec close enough to what you are doing to cover everything;  this way, if we have to iterate once or twice on the change, we can expedite things by my sending you hpi files directly

**Comment by gabemontero** [comment]
just unzip that file and then install the hpi file as you usually do ... thanks

**Comment by livelace** [comment]
Values in advanced tab - http://fastpic.co/image/Ph0k16
Error1 -
https://paste.fedoraproject.org/paste/N9mDtmSMi6uwgwVmqn8Yel5M1UNdIGYhyRLivL9gydE=/raw
Error2 -  https://paste.fedoraproject.org/paste/AP4U~0iJjOzOZqMcvQbDC15M1UNdIGYhyRLivL9gydE=/raw

**Comment by livelace** [comment]
@gabemontero I go sleep now. Feel free to attach a new version - I will check it in the morning :)

**Comment by gabemontero** [comment]
There is a long to int conversion issue with error1 (the restclient only takes int) ... I might be able to work around error1 by converting the long / milliseconds to a smaller number in larger units.

with error2 I'm inferring you put quotation marks around your number ... not sure otherwise

**Comment by gabemontero** [comment]
but in general you'll need to be a little careful with the timeout value you put in ... there is only so much massaging that can be done in this space.

here is the updated plugin:  
[jenkins-plugin.zip](https://github.com/openshift/jenkins-plugin/files/1012420/jenkins-plugin.zip)

**Comment by livelace** [comment]
@gabemontero It works! Tasks work as expected. Today I will work with this step in more intense manner, maybe it will reveal hidden problems, but it works at the moment :) 

Thank you very much :)

**Comment by livelace** [comment]
@gabemontero 

I think enough. All working fine. 

Have a nice weekend :)

**Comment by gabemontero** [comment]
On Fri, May 19, 2017 at 6:51 AM Oleg Popov <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero>
>
> I think enough. All working fine.
>
> Have a nice weekend :)
>
great thanks you too
