### ISSUE TITLE
Missing "install" section in README

### ISSUE THREAD

**Issue by mfojtik** [openshift/jenkins-plugin#14]
There is missing section about how to install this plugin to Jenkins. At least a link to https://wiki.jenkins-ci.org/display/JENKINS/OpenShift+Pipeline+Plugin at the top of the README will be useful. 

Also it would be helpful to provide instructions to build this plugin from the master ;-) (for us, no-jave folks).

**Comment by gabemontero** [comment]
@mfojtik - I pushed a README update with https://github.com/openshift/jenkins-plugin/commit/c67b0578789ac22ae9484da7a442456a572ec920

Take a peek and if you have further suggestions, I'll incorporate them before closing this issue out.

thanks
