### ISSUE TITLE
Issue with Jenkin's Verify Build OpenShift plug-in functionality

### ISSUE THREAD

**Issue by mexicanopelon** [openshift/jenkins-plugin#153]
We are having a recurring issue with Build Verify OpenShift functionality.  The Jenkins job is able to successfully kick off the OSE builds, but for some reason it tracks the incorrect build job instead of the latest one.  Therefore, even though the build job succeeds, the Jenkins job fails because it is waiting for the wrong job to succeed.

We were able to confirmed that there is a bug with the OSE plugin.  It is around how it sorts the list of builds.  It does it alphabetically instead of timestamp.  Therefore, for example, it places build-4 before build-38.

**Comment by srang** [comment]
If I had to guess the issue may lie here:
- [the mapping](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftBuildVerifier.java#L46-L50)
- [and sorting](https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/model/IOpenShiftBuildVerifier.java#L57)

**Comment by gabemontero** [comment]
@mexicanopelon and @srang - thanks for the report, and the analysis which zero'ed in on the issue!

I should have a PR cooking shortly, followed by a new plugin version hosted at the jenkins update center, followed by an update of the openshift jenkins centos image.

**Comment by mexicanopelon** [comment]
Thank you for the quick response.

**Comment by gabemontero** [comment]
@mexicanopelon @srang I'll cut the new version of the plugin at the jenkins download center later today or early next week, but the change is available at this repo now if you are interested in building (via `mvn clean package`) and install the hpi file manually.

**Comment by gabemontero** [comment]
v1.0.52 of the plugin is now available at the jenkins download center

**Comment by gabemontero** [comment]
and the openshift jenkins centos image on docker hub should be updated within the hour, assuming no network issues, etc.

**Comment by srang** [comment]
Woooo thanks Gabe! We'll update our plugin and test it out

**Comment by abustya** [comment]
Will the rhel7 image also be updated?
I'm using openshift3/jenkins-2-rhel7 (from jenkins-ephemeral-template), and the plugin version included is 1.0.47.

**Comment by bparees** [comment]
@abustya yes, when OCP3.7 ships there will be a new jenkins rhel image available and it will include this change.
