### ISSUE TITLE
openshift-client-plugin really still a "tech preview" ?

### ISSUE THREAD

**Issue by elconas** [openshift/jenkins-plugin#157]
The readme.md states:

> To that end, the new experimental [OpenShift Client Plugin for Jenkins](https://github.com/openshift/jenkins-client-plugin) is now offered as a **technical preview** and is included in the OpenShift Jenkins images on Centos

Is this still true as the openshift-client-plugin was released 1.0.0 on 2017-09-27 and the openshift-client-plugin calls this plugin a "legacy plugin":

From https://github.com/openshift/jenkins-client-plugin
> If you are interested in the legacy Jenkins plugin, you can find it
[here](https://github.com/openshift/jenkins-plugin).  

I guess openshift-client-plugin is the way to go, so anything stopping it from beeing used in Production in version 1.0.0 and above ?

**Comment by gabemontero** [comment]
Yeah, with the upcoming 3.7 release of OpenShift (to be release any day now) we are declaring openshift-client-plugin supported (no longer experimental).

It will be officially supported in production envs at that point.  

And yes, we'll need to update this readme to reflect that.  And yes, while this plugin is still supported, openshift/jenkins-client-plugin is the strategic direction.

**Comment by lionelve** [comment]
I can't find a nice way to replicate the functionality of openshiftVerifyDeployment in the new plugin. It'd be a shame to lose the features that this plugins does well. 

UPDATE:  Turns out oc rollout makes this very easy with the new plugin. It watches by default. 
```groovy
openshift.withCluster() { 
  openshift.withProject('myproject') {
    openshift.raw('rollout status dc/nodejs')
  }
}
```

**Comment by bparees** [comment]
> I can't find a nice way to replicate the functionality of openshiftVerifyDeployment in the new plugin. It'd be a shame to lose the features that this plugins does well

This plugin won't be going anywhere for a while, we're just not going to be adding new capabilities.

Longer term, what we want to do is make the "oc" client binary more capable of these type of actions (verifying things, waiting for things to complete, etc).  After all, someone scripting usage of oc outside of a jenkins job might want to verify a deployment too.  Then the openshift client plugin would naturally inherit those capabilities.

@gabemontero assigning this to you for any cleanup that needs to be done in both plugin readmes to reflect the deprecated status of this plugin and the GA status of the client plugin.
