### ISSUE TITLE
OpenShiftCreator assumes /oapi/v1 endpoints

### ISSUE THREAD

**Issue by warmi01** [openshift/jenkins-plugin#2]
OpenShiftCreator.java sets up the target URL endpoint using a /oapi/vi/ path string:

url = new URL(apiURL + "/oapi/v1/namespaces/" + namespace + "/" + path + "s");

However, when parsing a JSON List that contains a "Service" item, this undefined endpoint cannot be resolved (404) using /oapi/v1/namespaces/[namespace]/services (OpenShift).

The endpoint can be resolved using the Kubernetes (/api/v1) API endpoint: /api/v1/namespaces/[namespace]/services

Question..

Should there be a 'services' endpoint exposed in oapi/v1 or should this code use the api/v1 endpoint for "Service" requests?

**Comment by gabemontero** [comment]
fixed via https://github.com/openshift/jenkins-plugin/commit/e720e3b6022bff59740dc51d7acdf91c53f8dd9d
