### ISSUE TITLE
FR: Command execution inside specific pod

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#20]
Hello. What I need in my QA work:

Workflow:
1. Build image.
2. Deploy replication controllers with services (HTTP, FTP, SMTP etc.)
3. Run specific Pod with my application inside. I want to exec commands inside this Pod, which will be test my application for establishing a connection with services (step 2). And pipe output back to jenkins. 

Maybe execution should be attached to Pod labels and execute command on bunch of Pods.

**Comment by livelace** [comment]
Inspired by:

https://github.com/jenkinsci/docker-workflow-plugin
https://github.com/fabric8io/kubernetes-workflow

**Comment by gabemontero** [comment]
@bparees @mfojtik FYI

**Comment by bparees** [comment]
The request in general is valid(ability to oc exec, basically), but for your specific use case, i'm wondering if you can use post-deployment hooks instead?  Did you look into that and find it wouldn't work for your needs?

We're also going to introduce a "test deployment" variant on deployments which is targeted at exactly this use case.  @smarterclayton or @ironcladlou might be able to provide more details on the status of that feature.

**Comment by livelace** [comment]
Yes, I used hooks previously. But it is not so flexible as Jenkins parameterized task.
I think that "test deployment" - is exactly what need our team.

**Comment by mfojtik** [comment]
@livelace this sounds like a job for the kubernetes plugin. If your image has java/jenkins agent, you can configure Jenkins to start it as a Pod and then define shell script job in Jenkins to do stuff you described.

**Comment by livelace** [comment]
@mfojtik 

I thought so at the start of investigation. But it is not working for me:
1. I don't have Jenkins slave agent inside my container, it is not necessary for job. My application should run alone.
2. I can't to cancel this pod through Jenkins build steps.

Now, I reached schema:
1. Build image by webhook.
2. Launch deployments with services.
3. Launch deployment with my application which will launch hook with tests (interaction with services on step 2). Save results of tests into persistent volume.
4. Cancel deployments (step 2/3).

If I could:
1. Launch pod (on step 3) and execute commands inside this container which I set through Jenkins build step and report directly to Jenkins - it will be great. I will get more flexible features  than predefined deployments configurations with hooks inside.
2. Cancel this job.

**Comment by livelace** [comment]
@smarterclayton and @ironcladlou can you explain "test deployment" feature ?

**Comment by livelace** [comment]
Ok, at this moment I do that: https://github.com/livelace/virtualization/blob/master/openshift/drweb/projects/drweb-configd-centos/drweb-configd-centos.yaml#L54

But it isn't comfortable, I think, that it can be installed as an option of Jenkins task.

**Comment by gabemontero** [comment]
Note, this request is captured on our trello board at https://trello.com/c/Yl4qomsw/878-5-additional-jenkins-plugin-enhancement-requests-from-github

**Comment by livelace** [comment]
It will be nice. Today we set path to script statically (inside DC), it is not very convenient. Also, if it will be provide timeout settings ... it will be very happy day :)

**Comment by gabemontero** [comment]
closing out - will track with trello card noted on Jun 13th
