### ISSUE TITLE
Support username and password credentials

### ISSUE THREAD

**Issue by elyscape** [openshift/jenkins-plugin#21]
Currently, the Jenkins plugin only supports using a token to authenticate itself to the OpenShift master. This is fine if Jenkins is being run from inside OpenShift, but if you have an external Jenkins instance, you have to deal with figuring out how to populate the auth token with a value that expires (by default) every 24 hours. It would be great if the plugin were extended to support authentication via a username and password from the credential store. Ideally, it would log in to the OpenShift master, execute whichever commands, and then log out to destroy the auth token.

In the meantime, I've worked around this by setting up a pipeline job that runs every 12 hours, gets a username and password from a credential entry, logs in to the OpenShift master via curl, parses out the auth token, and stores it in a plain credential. It requires [the pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin), [the credentials binding plugin](https://wiki.jenkins-ci.org/display/JENKINS/Plain+Credentials+Plugin), and [the plain credentials plugin](https://wiki.jenkins-ci.org/display/JENKINS/Plain+Credentials+Plugin). It's also super janky due to limitations of the pipeline plugin (e.g. no ability to get command output, so you have to redirect into a file). Here's the job, in case anybody needs to do this for now:

``` groovy
def token

node {
  withCredentials([[$class: 'UsernamePasswordBinding', credentialsId: 'USER_PASS_CRED_ID', variable: 'OCCREDS']]) {
    sh '''
      curl -v -XGET \\
        --no-keepalive \\
        -u "${OCCREDS}" \\
        -H "X-Csrf-Token: 1" \\
        'https://OPENSHIFT_MASTER:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client' \\
        2>&1 | \\
        grep 'Location: ' | \\
        sed -E 's/.*access_token=([^&]+)&.*/\\1/' >token
    '''
    token = readFile 'token'
    token = token.trim()
    sh 'rm token'
  }
}

def cred = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
  org.jenkinsci.plugins.plaincredentials.StringCredentials
).find { it.id == 'AUTH_TOKEN_CRED_ID' ? it : null }

def credstore = jenkins.model.Jenkins.instance.getExtensionList(
  'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
)[0].getStore()

def newcred = new org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl(
  cred.scope,
  cred.id,
  cred.description,
  new hudson.util.Secret(token)
)

credstore.updateCredentials(
  com.cloudbees.plugins.credentials.domains.Domain.global(),
  cred,
  newcred
)
```

On any jobs that you want to use this credential, you bind the plain string credential containing the token to the `AUTH_TOKEN` environment variable.

**Comment by gabemontero** [comment]
@bparees @mfojtik FYI

A couple of preliminary points:
1) short term, the openshift-restclient-java component already has user/password support; the effort would be simply exposing means through the UI to store those values for the build steps

2) haven't looked in detail yet, but I suspect this falls in line with @mfojtik 's comment about how the k8s plugin leverages the credentials plugin and that we probably should do the same

 in any event, it certainly is a call to move beyond the pre-plugin sample job that only leveraged token based auth

**Comment by bparees** [comment]
sounds reasonable to me.

**Comment by livelace** [comment]
Up. Very inconvenient with tokens. We have about 40 builds + 30 deployment configurations - it's hell of tokens.

**Comment by bparees** [comment]
> Up. Very inconvenient with tokens. We have about 40 builds + 30 deployment configurations - it's hell of tokens.

i take it you can't simply grant permissions to a single token to access all of those builds and deployments?

**Comment by livelace** [comment]
I wanted do that at first step, but after some reflections I decided to set permissions separately, by projects (some users can to do some things in other projects too). At this moment it is working, but after I see Jenkins tasks, I can't definitely understand who from users can tag "IS" or can launch "DC", it is impersonal, I need username and password.

**Comment by gabemontero** [comment]
As an FYI, we are tracking this request with [this trello card](https://trello.com/c/QjgmeISb/884-more-credential-mgmt-wrt-jenkins-plugin)

**Comment by gabemontero** [comment]
closing out ... tracking with trello card

**Comment by gabemontero** [comment]
closing issue - will track via previously noted (on May 16) trello card
