### ISSUE TITLE
Add support for "Delete OpenShift Resource(s)"

### ISSUE THREAD

**Issue by bdeneuter** [openshift/jenkins-plugin#24]
At the moment there is support for creating resources in the plugin (oc create -f), but there is no support for deleting resources (oc delete -f).
It would be nice to have this command also available.

**Comment by gabemontero** [comment]
@bparees FYI

**Comment by livelace** [comment]
Up. Necessary functionality. And I say more, we need that after environments launching we should be able stop/destroy the environment or components of the environment (builds, images, pods etc.).

**Comment by livelace** [comment]
- preferably as build steps

**Comment by gabemontero** [comment]
@bdeneuter and @livelace :  I've got a question related to your potential preferences on how to capture what to delete.  Would you say prefer:
a) to specify the same json/yaml content you provided to the create resources command, or 
b) to specify a simple list of api object type:api object key pairings, or
c) to have both input methods, or 
d) some other form I'm not thinking of

**Comment by livelace** [comment]
Hello.

a) It's needed, I think.
b) I not sure what that means. Can you add examples ? 
d) I think, if I can just type DC (other object name)  for deletion - it' will be great.

**Comment by gabemontero** [comment]
@livelace for b) something like "ImageStream:frontend,BuildConfig:frontend,DeploymentConfig:frontend,DeploymentConfig:frontend-prod"

for d) do you mean simply type in "DeploymentConfig", and we would delete all the DeploymentConfigs in the project?

**Comment by livelace** [comment]
Your "b" - it's what I mean in my "d".  Conclusion:

a) to specify the same json/yaml content you provided to the create resources command, or 
b) to specify a simple list of api object type:api object key pairings ("ImageStream:frontend,BuildConfig:frontend,DeploymentConfig:frontend,DeploymentConfig:frontend-prod")

I think that it will be sufficient for us.

**Comment by bparees** [comment]
Seems like we should just have the resource-type/resource-name pairings, not sure what benefit users would get from providing the entire resource definition yaml?

**Comment by livelace** [comment]
> not sure what benefit users would get from providing the entire resource definition yaml?

Hm, I thought about this situation and I think that will be useful for conveniences. With json/yaml (which may be huge with a lot of elements) I don't must review all objects inside and I can just put its content into Jenkins job.

**Comment by bparees** [comment]
@livelace ok.  i guess i can see the argument for it as a secondary capability.

@gabemontero another thing to consider is allowing users to provide a label to match for deletions, like you can do on the CLI.  That makes it easier to delete everything a template instantiated, for example.

**Comment by gabemontero** [comment]
OK, I've built a pre-release version that is stored [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/lastSuccessfulBuild/artifact/plugin/openshift-pipeline.hpi)

It is based off of https://github.com/openshift/jenkins-plugin/commit/b77af1c362bf1276edeb5cc45db8bb08224e525a

Don't know the precise schedule yet of when we'll start updating the OpenShift Jenkins image again with new versions of the plugin, but my best guess would be in the later May or June timeframe.

**Comment by bparees** [comment]
@gabemontero we can do a new centos image anytime you're confident in the plugin :)
