### ISSUE TITLE
Add Support for env in oc start-build

### ISSUE THREAD

**Issue by eformat** [openshift/jenkins-plugin#27]
FR: add support for passing environment variables to the "oc start-build" command

**Comment by mfojtik** [comment]
oc start-build command already support -e.
do you mean add support to Trigger a Build step in Jenkins?

**Comment by eformat** [comment]
this isn't exposed via the jenkins-plugin though - from what i can see ?

https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/OpenShiftBuilder.java#L244

one use case may be a binary deployment of a WAR file - where you can pass the WAR_FILE_URL to the builder. there are many others.

**Comment by gabemontero** [comment]
Correct  - those options are not yet exposed through the jenkins-plugin builder step.

**Comment by gabemontero** [comment]
This request is being tracked by the trello card https://trello.com/c/Yl4qomsw/878-5-additional-jenkins-plugin-enhancement-requests-from-github

**Comment by gabemontero** [comment]
closing out issue ... will track via trello cards

**Comment by gabemontero** [comment]
This request has been implemented with https://github.com/openshift/jenkins-plugin/commit/4060fdac332229ff5eadc230586fa29813e57f34
