### ISSUE TITLE
FR: Support for cross-project tag

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#30]
Subject. At this moment we can create new tag inside one project but can't do this between projects. Use case: dedicated projects for building images.

**Comment by gabemontero** [comment]
This has been added to the plugin with commit https://github.com/openshift/jenkins-plugin/commit/80b79c6fd8c54b189740611a17830cfdcb315352

We just have not built an official OpenShift Jenkins images with a version of the plugin that contains this enhancement yet.

I can post a built version of the plugin with this change if you like - just let me know.

**Comment by livelace** [comment]
> I can post a built version of the plugin with this change if you like - just let me know.

It will be great! Thanks.

**Comment by gabemontero** [comment]
[Here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/9/artifact/plugin/openshift-pipeline.hpi) is a built hpi file that you can install on top of the existing one in the jenkins image.

Also note [these instructions](https://github.com/openshift/jenkins-plugin#authorization) with respect to making sure the plugin has the appropriate authorization to manipulate ImageStream's in two separate projects.
