### ISSUE TITLE
Long-lived process of build has fault status

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#32]
Step to reproduce:
1. First build about 10 minutes (no Docker cache): completed in Openshift, failed in Jenkins (https://paste.fedoraproject.org/349217/53140145/)
2. Second build about 1 minute (Docker cache): completed in Openshift, completed in Jenkins (https://paste.fedoraproject.org/349218/45975318/).

**Comment by gabemontero** [comment]
Hello @livelace - took at look at the data provided, and could see this going one of two ways:

1) For the longer running build, did you increase the wait interval as documented [here](https://github.com/openshift/jenkins-plugin#communication-timeouts) ?  If not, the solution could be as simple as that.  Also, in looking at those timeout settings, `OpenShift Builder` is for the `Trigger OpenShift Build` step that you were using in your examples above.  `OpenShift Build Verification` is for the `Verify OpenShift Build` step.

2) If the "null" status occurs with the wait intervals sufficiently increased, then we'll need to investigate the operations of the OpenShift builder pod, and get some traces/logs from that end.

**Comment by livelace** [comment]
Yes, you are right. It's my mistake, I completely forget about global settings. All working fine.

**Comment by livelace** [comment]
NaB
