### ISSUE TITLE
FR: Dedicated timeout settings for tasks

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#34]
SUBJ. At this moment we have global settings for tasks, but it is very inconvenient.

Use case: We have build1, we should set high time out for that build. We have build2, which failed, but we should wait global time out, which we set for build1.

**Comment by livelace** [comment]
@gabemontero Hi, how you think, how much time it will take ? I have 10 builds at this moment, but I expect about 50 in near future :)

**Comment by gabemontero** [comment]
Might be able to get to it today @livelace  .... I'll keep you posted.

**Comment by gabemontero** [comment]
ok .... provided with https://github.com/openshift/jenkins-plugin/commit/5f60b1eed88a65bb9dd28ede4a86caea4a1e5912

pre-release version built and stored [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/lastSuccessfulBuild/artifact/plugin/openshift-pipeline.hpi)

We'll probably start updating the OpenShift Jenkins image sometime in May.

**Comment by livelace** [comment]
@gabemontero Big thanks. It's great news :)
