### ISSUE TITLE
Doesn't detect build error before expiry timeout

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#37]
What happen:
1. Set global timeout - 3 hours.
2. Launch build.
3. The build ended with error.
4. Jenkins is waiting 3 hours, to detect error.

Can we detect errors at once, don't wait timeout expiration ?

**Comment by gabemontero** [comment]
Yep, I think I can get to this either today or Tuesday local time for me.

**Comment by gabemontero** [comment]
Fix delivered to repo via [this commit](https://github.com/openshift/jenkins-plugin/commit/d0481f7fb63ed27bf8d3f38370cf7b80abbb0331)

Pre-release built version of the plugin is [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/lastSuccessfulBuild/artifact/plugin/openshift-pipeline.hpi)

Most likely I'll start the next official release cycle for the plugin in the next day or so (have a few other fixes to package as well).  The official release of the plugin with this fix will be v1.0.11.

**Comment by gabemontero** [comment]
FYI v1.0.11 is out and the openshift centos jenkins image has been updated with it.

**Comment by livelace** [comment]
@gabemontero Big thanks :)
