### ISSUE TITLE
FR: Post-build Actions - Scale Development

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#38]
Hello. 

Current workflow:
1. "job-run" - scale development to 1, do something, call "job-down" in any situation (exit 0/1).
2. "job-down" - scale development to 0, do something. 

Why we can't do this in one job, steps:
1. Scale development to 1 
2. Execute a shell script, which return status of execution on step 1  
3. Scale development to 0

If error will appear on step 2 (exit 1), the step 3 will not be executed and all deployments will stay in working state.

Therefore we should write and maintain two jobs (up/down) instead of one. From this arise problems for batch execution of many of jobs ("job-run" tasks stayed alive until will not be executed "job-down" tasks).  

We need post-build action - "scale development".

**Comment by gabemontero** [comment]
Yeah, I _could_ see having both a build step and post-build action version of `oc scale` (where today we just have the build step.

@bparees FYI

**Comment by bparees** [comment]
yeah sounds reasonable.  In the meantime of course you can do a post-build shell script step that invokes oc to scale the deployment down, to avoid having a second job, right?

**Comment by gabemontero** [comment]
Correct @bparees re: post build shell script invoking `oc scale`

**Comment by livelace** [comment]
> yeah sounds reasonable. In the meantime of course you can do a post-build shell script step that invokes oc to scale the deployment down, to avoid having a second job, right?

Jenkins is working on other host and assemble hack with remote "oc scale" ... authentication with superadmin/cluster-admin rights ... I think we will wait post-build steps, because double jobs already created and extra manipulation not needed.

**Comment by livelace** [comment]
It's more complicated than just "oc scale", because in addition we should verify (  "Verify whether the specified number of replicas are up", oc scale --replicas=0) that deployment completely stopped and after that do something with a data, which was appeared after work of deployment.

**Comment by livelace** [comment]
up

**Comment by gabemontero** [comment]
Yeah, this could be a fairly quick one.  Things are shaping up that I'll have some cycles for this one in the next day or two.

**Comment by livelace** [comment]
@gabemontero Big thanks! Just it is last part before we will add bulk of tasks.

**Comment by gabemontero** [comment]
@livelace - this [pre-release version](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/lastSuccessfulBuild/artifact/plugin/openshift-pipeline.hpi) should contain [this commit](https://github.com/openshift/jenkins-plugin/commit/97116cb5f90742de23adfbde5a940d4ac5a6107d), which introduces the "Scale OpenShift Deployments" post build action.

Closing this out.
