### ISSUE TITLE
Add option to ignore SSL errors

### ISSUE THREAD

**Issue by ikke-t** [openshift/jenkins-plugin#39]
I tried using these plugins for Dev -> Test -> Prod process flow. They fail if the OSE cluster has self signed certs. It would be fixed eg. by having checkbox to pass "--insecure-skip-tls-verify" option to oc command in each plugin.

"As a user, I would like to have option to ignore SSL errors in each plugin."

ERROR: Build step failed with exception
com.openshift.restclient.OpenShiftException: javax.net.ssl.SSLHandshakeException while trying to get an authorization context for server https://xxx.ose-demo.xxxxdemo.com:8443

**Comment by ikke-t** [comment]
I got pointed to this README file https://github.com/jenkinsci/openshift-pipeline-plugin/blob/master/README.md#certificates-and-encrpytion , which seems to have a way around this. I'll try.

**Comment by gabemontero** [comment]
I was just about to point you that link :-)

Let us know what happens.

**Comment by ikke-t** [comment]
SKIP_TLS=true fixes it. I just wonder why, as I verified that the cert in jenkins container: /run/secrets/kubernetes.io/serviceaccount/ca.crt and ose master:/etc/origin/master/ca.crt are the same.

**Comment by gabemontero** [comment]
ok cool @ikke-t 

On your cert question, it is a function of how your OpenShift is set up and how it mounts secrets into any Pod (including the one Jenkins is running in), independent of the plugin.

See https://docs.openshift.com/enterprise/3.0/dev_guide/service_accounts.html#managing-service-account-credentials

@bparees please keep my honest / correct as needed.
