### ISSUE TITLE
FR: Using variables as substring in names of configurations

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#49]
Hello. At the moment we can use variables like this: 

```
VERSION=centos

The name of the DeploymentConfig to scale: VERSION
```

But we can not do like this:

`The name of the DeploymentConfig to scale: drweb-fss-VERSION or drweb-fss-$VERSION or drweb-fss-${VERSION} or drweb-fss-${VERSION}-rpm`

We have a lot of similar tasks, which are different only in software version.

**Comment by gabemontero** [comment]
sure, I could see supporting both $VERSION and ${VERSION} style embedded variables for parameter values (EnvVars and the standard plugins in this space support both) with little trouble.

I'll most likely start cooking a new version of the plugin for some recent fixes in the next couple of days.  I'll see if I can incorporate this change as part of that.

@bparees FYI

**Comment by livelace** [comment]
@gabemontero Thanks! :)

**Comment by gabemontero** [comment]
YW @livelace 

By the way, after digging some more, at least for mixed items like `drweb-fss-${VERSION}`, in experimenting with some of the existing Jenkins utilities, only `${VERSION}` works ... `$VERSION` works if that is the only thing in the string, but not in the mixed case.

So I'll just support `${VERSION}` for mixed items.

**Comment by livelace** [comment]
@gabemontero  

Cool! It will allow us to shrink a lot of Jenkins jobs to task with parameters :)

**Comment by gabemontero** [comment]
OK, I've delivered the change with https://github.com/openshift/jenkins-plugin/commit/474c088557c7a2059e5c5ff065971603d01ea91d

Aside from the code change, I updated the README's `Providing parameter values` section, clarifying the new behavior.

I've created a pre-release version of the plugin at https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/25/s3/download/openshift-pipeline.hpi

I'm going to be starting the official release process probably Thursday, but if you can try the pre-release version before that @livelace , let me know if you see any issues, etc. and I'll make updates as needed.

thanks

**Comment by livelace** [comment]
Hmm. It seems working. Multiple variables working fine in name of: deployments, builds, image tags. Old tasks are working too. Thanks!

**Comment by gabemontero** [comment]
Great - thanks for trying it out!
