### ISSUE TITLE
Does not detect build failure ? 

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#51]
```
 ---> 6073f754f5be
Removing intermediate container 08ba9ce0ddef
Successfully built 6073f754f5be
I0719 05:35:47.252709       1 docker.go:118] Pushing image 172.30.208.158:5000/images/ready-drweb-fss-samba-3.4.0-rpm:11.0 ...

F0719 05:39:36.462583       1 builder.go:204] Error: build error: Failed to push image: Received unexpected HTTP status: 500 Internal Server Error
```

Jenkins task stays running. 1.0.21-SNAPSHOT (private-a1131ed0-ec2-user)

UP. Task ended with error according to global build timeout:

```
Exiting "Trigger OpenShift Build" unsuccessfully; build "ready-11.0-drweb-fss-samba-3.4.0-rpm-8" did not complete successfully within the configured timeout of "7200000" ms; last reported status:  [NotStarted].
ERROR: "Trigger OpenShift Build" failed
```

**Comment by gabemontero** [comment]
hey @livelace - I believe I see what the issue with respect to jenkins job not ending relatively soon after the registry error.

I am out of the office on vacation for a few days while I move to a new house.  I can definitely get a fix ready next week, but if you are hitting this a lot and this is really impacting you, let me know and I'll see about squeezing in some time this week to build you a fix.

**Comment by livelace** [comment]
@gabemontero  Absolutely not, it was one failed case among a lot of success.

**Comment by gabemontero** [comment]
@livelace I've got a pre-release version with the fix located [here](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/27/s3/download/openshift-pipeline.hpi)

Based on commit https://github.com/openshift/jenkins-plugin/commit/a571787293a757c4cf2a127bfccddff1d4b9c49f

Going to close this out, but if you manage to try out the pre-release version and something seems incorrect, let me know.
