### ISSUE TITLE
default the namespace for the openshift plugin operations when we're executing in a pipeline that has a namespace associated

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-plugin#54]
Some background from @bparees 

```
just because your pipeline buildconfig is defined in one project, doesn't mean that the builds that pipeline triggers are going to reside in the same project.  So while it might be a nicer default to assume it is, the reality is there will still be cases where people are going cross-namespace.

what you really have is 3 namespaces:

1) namespace where jenkins is running
2) namespace where the pipeline buildconfig is defined
3) namespace(s) where the "real" build(s) are defined

any of which could be the same or different.

Today we behave/default to assume that 1+3 are the same.  You're asking us to assume 2+3 are the same.  Which i agree is a slight improvement for some cases, again assuming it's even technically possible for us to hand that information between the sync plugin and the openshift plugin. Gabe would know more about that.
```

and from @jimmidyson 

```
The sync plugin already attaches info about the OS build to the
Jenkins build cause so you could get the info from there quite easily.
```

There is also an internal write up from @siamaksade on his attempts to set up pipeline project with an external jenkins.

**Comment by gabemontero** [comment]
I've found BuildCause.java in the openshift-sync code and am working on a patch to pull that from the Run object and update the namespace if it is present.  I'd rather call BuildCause.getNamespace() vs. parsing the short description that is available with the base hudson Cause class, so I'm first trying to make openshift-sync a dependency for openshift-pipeline (which will test my still young maven/pom skills :-) as the typical way I've created dependencies is not working at the moment ).  Later on, if we are worried about size or circular dependencies, switching to parsing the short description is always a fallback option.

The order of precedence I'm envisioning is:
1) if customer explicitly sets the namespace, go with that 
2) if sync plugin sets i cause, go with that 
3) go with the two existing default mechanisms (PROJECT_NAME env or namespace file mounted in the Pod

**Comment by gabemontero** [comment]
got the maven dependency working :-)

**Comment by bparees** [comment]
> 1) if customer explicitly sets the namespace, go with that

sets it in the build step or sets it in the global plugin settings (if that's even a thing they can do)?

**Comment by bparees** [comment]
> Both in effect. The user puts some sort of value in any of our steps fields

ok but there's no way to define a global default value (not env variable) that the steps will use?

**Comment by gabemontero** [comment]
Not currently, since to date pulling the default from what is mounted in the pod has been acceptable.  But if isolating the project jenkins runs in from the "app" project has grown enough, we can special case the namespace and give it that means in addition to the env var stuff.

**Comment by bparees** [comment]
fine for now, just wanted to make sure the full precedence hierarchy was represented.  your proposal sounds good to me.

**Comment by gabemontero** [comment]
ok cool @bparees 

@siamaksade - I have pushed a [pre-release change](https://github.com/openshift/jenkins-plugin/commit/e212a50b64728c6343b0e251bcbb70e3656b4e3e) for the openshift pipeline plugin that should have it pull the namespace/project from the cause that the sync plugin sets before pulling it from what is mounted in the pod.

Download this [binary](https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/27/s3/download/openshift-pipeline.hpi) and upgrade the plugin being used by your jenkins install via the Manage Jenkins -> Manage Plugins path if you want to give it a try.

**Comment by siamaksade** [comment]
I'll give it a try and come back to you today

**Comment by siamaksade** [comment]
For the record, it worked as expected
