### ISSUE TITLE
FR: Delete objects with confirmation

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#57]
Case:
1. We create objects and they are working.
2. We send command to delete all objects. Not all objects (Pods) can be deleted immediately and some still are working and they are writing data(until their death). But we already reported about deletion and a next Jenkins task begins started, which want that data will not be changed. It's the problem.

**Comment by bparees** [comment]
it sounds like your scenario is effectively the same as running:

`oc delete pod foo`

and then while the command returns immediately, the pod keeps running for some period of time until it is killed.  Is that accurate?

If so, i think the only way we can do better here is to offer a way for you to "wait for termination" when deleting objects (we'd have to watch/poll to see when the object actually goes away).

Note that your containers should be getting a SIGTERM when the delete occurs, so if they are continuing to do work, they are ignoring that signal (in which case k8s gives them about 30s to terminate before it hard-kills them).  You might be able to modify the grace period such that the pod is immediately terminated instead, as a workaround.

**Comment by gabemontero** [comment]
(will create trello card or incorporate into existing card if applicable once we lock down the detail or two @bparees asked @livelace about)

**Comment by livelace** [comment]
> and then while the command returns immediately, the pod keeps running for some period of time until it is killed. Is that accurate?

Yes, absolutely. The period depend on the node utilization, application inside pod ... etc In my case the problem is in parse xml file, which locked inside pod and the next Jenkins step can't handle it correctly.

> If so, i think the only way we can do better here is to offer a way for you to "wait for termination" when deleting objects (we'd have to watch/poll to see when the object actually goes away).

It sounds good.

**Comment by gabemontero** [comment]
I've opened [this trello card](https://trello.com/c/t9CWATta/1010-jenkins-plugin-delete-objs-with-confirmation) to track this request ... closing github issue out per process.

**Comment by bparees** [comment]
@livelace did you try setting the grace period to 0s?  i'm curious if that would fix your problem:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L160-L164

**Comment by livelace** [comment]
@bparees I didn't find the "deletionGracePeriodSeconds" parameter in my "ClusterPolicy". But I compared situation with deletion of objects.
1. for type in route rc dc svc pod;do for i in $(oc get $type | awk '{print $1}');do oc delete $type $i;done;done - one Pod which did some operations (postStart hook) was alive for 1-2 minutes in the "Terminating" state.
2. for type in route rc dc svc pod;do for i in $(oc get $type | awk '{print $1}');do oc delete --grace-period=0 $type $i;done;done - it killed all immediately

I think, that both parameters are needed, because someone wants to get completely finished writing of data, and someone wants to get the immediately deleted objects. 

I want that it could complete all tasks and shift to the next step :)

**Comment by bparees** [comment]
> @bparees I didn't find the "deletionGracePeriodSeconds" parameter in my "ClusterPolicy"

it's not a cluster policy setting, it's a setting on each resource (in this case the pod resource).

But yes if your pods need that grace period to properly clean up then setting it to zero won't be a valid workaround for your scenario, unfortunately.
