### ISSUE TITLE
FR: The dedicated timeout for deployment verification 

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#58]
@gabemontero 

At first, big thanks :+1:   "Verify Deployment Configuration" detects the "postStart" failure situation (regardless of the replica counter)! I checked twice! 

For now, we need the simple timeout parameter for the verification of deployment. It allows us to control each deployment (deployment in whole + postStart hook) configuration inside complex configuration.

**Comment by livelace** [comment]
Forgot to ask. Can we detect that deployment failed and don't wait the extra time ? 

Like in that case https://github.com/openshift/jenkins-plugin/issues/37

**Comment by gabemontero** [comment]
hey @livelace - commit https://github.com/openshift/jenkins-plugin/commit/8a31bd9b89af4f91d27155748278fce9f8505c44 and pre-release version https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/31/s3/download/openshift-pipeline.hpi
are ready for you to try.

thanks
