### ISSUE TITLE
FR: Tag images in multiple projects simultaneously

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#62]
Hello. The quantity of projects are growing and dedicated tag step for each project - it's not convenient. 6 projects and 20 different builds = 120 tag steps (all imagestream in all projects, except central image project).

**Comment by gabemontero** [comment]
@livelace are you thinking 
1) 1 src tag and many dst tags
2) N src tag and P dest tags, where N == P
3) both 1) and 2)
?

**Comment by gabemontero** [comment]
@bparees FYI

**Comment by livelace** [comment]
@gabemontero 
1. It will be great.
2. It's the very rare case, because we use metajobs, which launch one specific build for different software == 1 build and 1 imagestream as result.
3. It will be nice if we will have both possibilities: src 1+n, dst 1+n

**Comment by livelace** [comment]
Hello. Any news ? :)

**Comment by bparees** [comment]
@gabemontero is this reflected on one of the "jenkins enhancement" trello cards?  if not, let's get it there (or create a new one) and close this.

**Comment by gabemontero** [comment]
hey @livelace and @bparees - yeah originally I thought I might be able to squeeze this one in between official assignments but that proved to not be the case, and will remain as such given what's currently on my plate.

I'll review the existing trello cards first, see if it makes sense to add this to those cards.  Otherwise, I'll create a new one.

I'll update this issue in a bit with the trello card in question and close this out.

**Comment by gabemontero** [comment]
OK, @bparees and I agree we can add this to https://trello.com/c/Yl4qomsw/878-5-additional-jenkins-plugin-enhancement-requests-from-github, which is already on our Next list, and so is pretty close to getting scheduled.

**Comment by gabemontero** [comment]
@livelace - an update.  With commit https://github.com/openshift/jenkins-plugin/commit/1da103810da471618db2122583d88abf2efd40db from @jupierce the plugin is now enabling the following forms:
1. 1 destination stream and 1 destination tag (i.e. single tag applies to single stream)
2. 1 destination stream and N destination tags (i.e. all tags apply to the same stream)
3. 1 destination tag and N destination streams (i.e. all streams will get the same tag)
4. N destination streams and N destination tags (i.e. each index will be combined to form a unique stream:tag combination)

**Comment by livelace** [comment]
Cool things. Thanks guys! :)

**Comment by livelace** [comment]
@gabemontero @jupierce 

Hello. I did update to the version 1.0.23 and don't see anything in the build step for tagging in multiple projects. This FR realized only in pipeline working mode ?

**Comment by jupierce** [comment]
@livelace Clicking the help icon next to the destination stream & tag in Jenkins should now describe support for a comma delimited list in each field.
A description of how the lists are handled is given in the pipeline section of the README.MD (https://github.com/openshift/jenkins-plugin ; search for "Tag OpenShift Image") -- the pipeline DSL supports an identical comma delimited list for the fields.

**Comment by jupierce** [comment]
@gabemontero just talked to me offline and pointed out that you specifically mentioned "projects" . You are correct that there is currently no support for multiple src/dest projects in the build step (or pipeline DSL for that matter). Only one source project and one dest project is supported in each step.

Based on the issue conversation, it seemed that enabling 1->N, N->1, N->N  (destStream->destTag)   would be sufficient. Please let us know if I've missed the mark.

**Comment by livelace** [comment]
Oh no. I meant projects and multiple tags between them. I thought we discussed all relations in context of projects. Because we have a lot of projects and one contain images, which must be available for others.

**Comment by jupierce** [comment]
@livelace You might be able to accommodate your project topology using the new feature and a pipeline DSL step/looping constructs, but if not, can you open another issue to enable multiple destination projects in the same tagging step? 
The necessary change will require us to go back to the drawing board for a bit in order to ensure backwards compatibility with prior versions of the plugin.

**Comment by livelace** [comment]
@jupierce  We can't move to using the pipeline right now. Maybe in near future. Ok, we will be use multiple steps.  Thanks.
