### ISSUE TITLE
Pipeline DSL documentation

### ISSUE THREAD

**Issue by jamestenglish** [openshift/jenkins-plugin#63]
The documentation for the new Jenkins 2.x documentation is all over the place.

There is this blog post, which is now wrong and outdated: https://blog.openshift.com/pipelines-with-jenkins-2-on-openshift/

This lists _bldCfg_ as the parameter for openshiftBuild but your README references _buildConfig_
https://jenkins.io/doc/pipeline/steps/openshift-pipeline/

Which one is correct?

In the RedHat OpenShift Workshop it says the best practice is to build the image then run your tests inside the image to control for environment changes, and the workshop shows that process with the OpenShift plugin running in Jenkins 1.x not using pipelines but I see no way to do that with the new 2.x pipeline DSL

Is there any good examples or documentation to how to best apply the OpenShift specific DSL?

**Comment by gabemontero** [comment]
Some responses embedded below.  @bparees and @jupierce fyi

On Monday, September 12, 2016, James English notifications@github.com
wrote:

> The documentation for the new Jenkins 2.x documentation is all over the
> place.
> 
> We are working a trello card this sprint to capture all the ci/cd related
> tidbits in a concentrated section of the openshift docs.
> 
> There is this blog post, which is now wrong and outdated:
> https://blog.openshift.com/pipelines-with-jenkins-2-on-openshift/
> 
> This lists _bldCfg_ as the parameter for openshiftBuild but your README
> references _buildConfig_
> https://jenkins.io/doc/pipeline/steps/openshift-pipeline/
> 
> Which one is correct?
> 
> Both are correct.  "bldCfg" was the original name with a pre release
> version.  API review switched to "buildConfig" but we kept "bldCfg" for
> early adopters.  I just double checked the readme and it lists both.
> 
> In the RedHat OpenShift Workshop it says the best practice is to build the
> image then run your tests inside the image to control for environment
> changes, and the workshop shows that process with the OpenShift plugin
> running in Jenkins 1.x not using pipelines but I see no way to do that with
> the new 2.x pipeline DSL
> 
> Is there any good examples or documentation to how to best apply the
> OpenShift specific DSL?

When i can get my laptop on a network Tuesday (i was traveling today I will
post the current example unless @bparees beats me to it.

**Comment by bparees** [comment]
@jamestenglish are you just looking for more details on the openshift plugin pipeline DSL syntax?
https://github.com/openshift/jenkins-plugin#jenkins-pipeline-formerly-workflow-plugin

we don't have a rich set of examples of using it, our primary pipeline example is here:
https://github.com/openshift/origin/tree/master/examples/jenkins/pipeline
https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/samplepipeline.json#L46

**Comment by jamestenglish** [comment]
I was looking for a more rich set of examples, but I guess it is was it is.

**Comment by gabemontero** [comment]
Ah - in that case, we have some in progress work this sprint that is focused just on that.

The trello card for it is [here](https://trello.com/c/cZvXM8zz/1022-5-pipeline-samples-techdebt) if you wish to track to on going work.

@csrwng FYI
