### ISSUE TITLE
Trigger OpenShift Build Options

### ISSUE THREAD

**Issue by anhnguyenbk** [openshift/jenkins-plugin#64]
Can I use options `--from-file` in Trigger Openshift Build.  I using external Jenkins for build and Openshift Origin just for binary deployment. I want to start Openshift build from Jenkins Plugin with options `--from-file`.

How could I do?

Thanks.

**Comment by gabemontero** [comment]
There as been another recent request for this.  It is not there currently.
I believe we are going to create a trello card and get this in the
scheduling pipeline.  @bparees fyi

**Comment by bparees** [comment]
Added to trello: https://trello.com/c/kJrtI2kF

**Comment by bparees** [comment]
@anhnguyenbk for now you'd have to use the oc command line tool and a shell build step to accomplish your goal.  The good news is that the oc client tool is already part of the openshift jenkins image.
