### ISSUE TITLE
Jenkins SCM Monitor OpenShift ImageStreams aren't available on workflow jobs

### ISSUE THREAD

**Issue by rawlingsj** [openshift/jenkins-plugin#7]
The [Jenkins SCM](https://github.com/jenkinsci/openshift-pipeline-plugin#jenkins-scm) Monitor OpenShift ImageStreams dont seem to be available when creating new Jenkins Workflow jobs.

**Comment by gabemontero** [comment]
Yeah, it was a little more complicated to to get that working with the workflow plugin.  I suspect we would have to leverage what is described [here](https://github.com/jenkinsci/workflow-plugin/blob/master/scm-step/README.md) in some fashion, but need to look into it more, and it would take enough time that I'll need to get it sized/prioritized.

I'm marking this as a request for enhancement - @bparees - FYI

**Comment by rawlingsj** [comment]
Ok thanks @gabemontero @bparees it would be great to see openshift jenkins plugin support for the jenkins workflow plugin, it's the direction cloudbees and fabric8 are taking for CD pipeline orchestration.

**Comment by gabemontero** [comment]
Yep, @bparees as been having discussions with the fabric8 folks regarding our overall Jenkins story which have included sucking in the workflow plugin into the OpenShift Jenkins image; enhancing the plugin's integration with the workflow plugin would then be an natural extension of this.  We just have to get work items officially prioritized and on the books.

@sspeiche - fyi -

**Comment by rawlingsj** [comment]
thanks @gabemontero yeah I'm one of the fabric8 developers and looking at how this plugin integrates with the CD features we've developed.  Being able to promote images from one project to another using workflow scripts is key, so I'm looking to see if this plugin can do that but I guess the answer is no.

**Comment by gabemontero** [comment]
At least for now - adding the equivalent of `oc import-image` and possibly `oc export` (per the outline from @mfojtik 's proposal) are what are needed.

BTW, I opened [this card](https://trello.com/c/7XIwg8Pn/780-3-make-jenkins-pipeline-plugin-s-imagestream-scm-accessible-from-the-workflow-plugin) on our trello board to track the image stream / scm piece.

And I opened [this card](https://trello.com/c/XDI6tvRy/781-2-add-equivalent-of-oc-import-image-to-the-openshift-jenkins-plugin) to track the import-image piece.

**Comment by rawlingsj** [comment]
great, thanks @gabemontero

**Comment by bparees** [comment]
i don't think oc import-image and oc export are what we're looking for.  

promoting an image between projects within a single cluster is handled via oc tag today.

promoting an image between projects across clusters is not something openshift itself includes any tooling to enable.  for now you'd need to docker pull/docker push the image to move it between registries.

so I don't think it's clear what we'd add to the jenkins plugin today to enable this, w/o underlying support in openshift.

**Comment by gabemontero** [comment]
closing out - tracking with 2 trello cards noted on Dec 11th.

**Comment by gabemontero** [comment]
@csrwng has delievered the change for this with https://github.com/openshift/jenkins-plugin/commit/6ee58601c3e4505ae331c4f6acf533178dd456bb

**Comment by rawlingsj** [comment]
Great - thanks @gabemontero @csrwng
