### ISSUE TITLE
Replace use of System.currentTimeMillis()

### ISSUE THREAD

**Issue by jupierce** [openshift/jenkins-plugin#76]
currentTimeMillis() is impacted by system clock changes (e.g. daylight savings changes). This can cause wait time calculations relying on the API to behave incorrectly. 
These loops can be changed to use System.nanoTime()    (with changes to accommodate nanoseconds instead of milliseconds values).

**Comment by gabemontero** [comment]
Interesting.  Ok, we'll add to the list.  I'll defer on assignment until the dust settles on all the concurrent work that is going on.

**Comment by bparees** [comment]
@jupierce i assume you used nanotime in the new plugin implementation?

**Comment by jupierce** [comment]
@bparees The new plugin shouldn't have this exposure. There are few timing loops in general because I expected users to use the base Jenkins "timeout" DSL or the timeout freestyle step wrapper. The plugin's step implementations just need to be interruptible (and should already be) in order to inherit the base timeout features.

**Comment by gabemontero** [comment]
This will be in v1.0.42 of the plugin.
