### ISSUE TITLE
promote apps to different projects

### ISSUE THREAD

**Issue by rawlingsj** [openshift/jenkins-plugin#8]
What's the recommended approach to promoting a images / apps across environments (openshift projects) using s2i and the openshift jenkins plugin?

I've seen this blog https://blog.openshift.com/promoting-applications-across-environments/ which uses a number of oc commands that I dont think are supported by the jenkins plugin so I was wondering how the promotion should work.

**Comment by gabemontero** [comment]
This is certainly still an involving space in relation to our overall Jenkins strategy.  Among other thing, @mfojtik has an [image promotion proposal](https://github.com/mfojtik/origin/blob/image-promotion/docs/proposals/image-promotion.md) that will most likely drive further enhancement into the plugin.

Certainly in the short term, in relation to the blog post you noted, the tag an image build step is the key piece in the existing plugin inventory that allows for some flavor of promotion semantics.  Template processing build steps minimally (a new-app build step would be nice but isn't required) would help complete the picture I agree.

@bparees @mfojtik @sspeiche - fyi and if you can, please add to / elaborate on my response here.

**Comment by gabemontero** [comment]
fyi opened [this card](https://trello.com/c/XDI6tvRy/781-2-add-equivalent-of-oc-import-image-to-the-openshift-jenkins-plugin) to track the minimal pieced needed in the plugin to facilitate image promotion per @mfojtik 's proposal.

**Comment by bparees** [comment]
`oc tag` (which the jenkins plugins already supports) should be all that's needed to promote images between projects within a single cluster.

The existing jenkins tutorial/sample implements an image promotion flow using that functionality.  

https://github.com/openshift/origin/tree/master/examples/jenkins

**Comment by gabemontero** [comment]
Yep I noted the tag an image build step (`oc tag` equivalent as well).  The `oc import-image` notion came from @mfojtik [image promotion proposal](https://github.com/mfojtik/origin/blob/image-promotion/docs/proposals/image-promotion.md).

But certainly an image promotion flow is available.  It becomes a question of how we augment that flow or add additional ones moving forward, no?

**Comment by rawlingsj** [comment]
Ah ok great - I'd missed that you can use tag to promote between projects, I thought it was only for the current project with that [blog](https://blog.openshift.com/promoting-applications-across-environments/) suggesting to create a new-app using the image stream name in the target environment (project).  

Great so tag is what I'm after so will use the following assuming I prefix the target project/environment in the prodTag var?

```
"Tag an image in OpenShift": com.openshift.jenkins.plugins.pipeline.OpenShiftImageTagger(String apiURL, String testTag, String prodTag, String namespace, String authToken, String verbose)
```

**Comment by bparees** [comment]
if it doesn't work that way today, it should be updated to take source and destination projecs as additional arguments.

**Comment by bparees** [comment]
@gabemontero @mfojtik I don't think "oc import-image mystream --from=mydockerrepository" is a likely way to do promotion.  you should already have an imagestream pointing to "mydockerrepository"

**Comment by gabemontero** [comment]
It only takes 1 project today ... I added another card:  https://trello.com/c/mImyw4Jx/783-1-allow-oc-tag-equivalent-in-openshift-jenkins-plugin-to-take-source-and-destination-projects-namespaces

**Comment by rawlingsj** [comment]
Great thanks all

**Comment by gabemontero** [comment]
With commit https://github.com/openshift/jenkins-plugin/commit/80b79c6fd8c54b189740611a17830cfdcb315352 , the "Tag OpenShift Image" step can now perform the `oc tag` equivalent where the src ImageStream and dest ImageStream are in different projects.

I've noted in the README some of the `oc policy` magic @mfojtik pointed me to that is needed to get a given default service account's token permission to access both projects in the necessary fashion to perform this step.

Aside from extracting from the repo and building the plugin, if desired, I can also create a new version of the plugin on OpenShift's Jenkins server (https://ci.openshift.redhat.com/jenkins/)

Otherwise, I suspect a new version of the Jenkins images with an official plugin version on the jenkins update center will be post 3.2 (though we can of course discuss as needed).

**Comment by gabemontero** [comment]
Closing this out.
