### ISSUE TITLE
Support Binary Builds 

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins-plugin#84]
I believe this is a feature request. If not, please do point me to the right documentation. I'd like to be able to perform the equivalent of `oc start-build <build-name> --from-dir=<local-directory>` using the `openshiftBuild` or a similar step.

**Comment by bparees** [comment]
thanks, we're already carrying this feature request on our trello board: https://trello.com/c/kJrtI2kF/1034-jenkins-plugin-binary-build-support
