### ISSUE TITLE
"Test Connection" button not working in my environment

### ISSUE THREAD

**Issue by jupierce** [openshift/jenkins-plugin#90]
Just fetched upstream and built including #83 

My environment:
- Running Jenkins outside of OpenShift
- Cluster is running with Cluster up
- SKIP_TLS=1 is configured a Jenkins global environment variable

Even though the build job works (ensuring I have a valid apiUIRL), test connection always reports "Connection unsuccessful" .

fyi @oatmealraisin

**Comment by gabemontero** [comment]
Jumped in to help on this one.  The global env variables are not getting put into the master env var list when the test connection descriptor impl is called.

I'm very reluctant to "assume" skip tls.

So we are going to try and reverse engineer where the global env vars are stored and see if we can access them through some new means.  

And at this juncture, I'm also reluctant to make skip TLS and/or the cert a first class step field.

If all else fails, I'm leaning toward putting the restriction that the test conn button only works when running inside openshift.

We'll report back when the investigations run their course, though there is a time limit of EOB today or early tomorrow, as we have to start cutting the new release.

**Comment by gabemontero** [comment]
OK, between @oatmealraisin and I we pieced together how to get the glob env var from the descriptor impl.

Should have a fix sorted out momentarily.

**Comment by gabemontero** [comment]
Have also added a change to get the default value from any job build params as well.  This way, users can provide the CERT via CA_CERT as an alternative to SKIP_TLS

**Comment by gabemontero** [comment]
fixed with https://github.com/openshift/jenkins-plugin/commit/01727d5775b4e1a1f40f09f745338f5497546924
