### ISSUE TITLE
Is it possible to capture the outcome of oc exec

### ISSUE THREAD

**Issue by schoeffm** [openshift/jenkins-plugin#93]
Hi all,

is it possible somehow to get the outcome of an oc exec in order to further decide how to proceed within the jenkins-pipeline.
Currently a call to openshiftExec does not seem to return anything - at the console I see what's happening, but is it possible to get the return status of the command which was executed?

Cheers

**Comment by jupierce** [comment]
@schoeffm That is not possible in the current implementation, but please follow #94 for information regarding the feature.
